### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/home/taimoor/.keras/datasets/cifar-10-batches-py/data_batch_1'

### ISSUE THREAD

**Issue by thassan66** [bryanyzhu/two-stream-pytorch#10]
I am running cifar10_cnn.py file using this command and getting following exception
THEANO_FLAGS=mode=FAST_RUN,device=cpu,floatX=float32 python cifar10_cnn.py 
Using TensorFlow backend.
Traceback (most recent call last):
  File "cifar10_cnn.py", line 37, in <module>
    (X_train, y_train), (X_test, y_test) = cifar10.load_data()
  File "/home/taimoor/anaconda3/envs/my_env/lib/python3.6/site-packages/keras/datasets/cifar10.py", line 26, in load_data
    data, labels = load_batch(fpath)
  File "/home/taimoor/anaconda3/envs/my_env/lib/python3.6/site-packages/keras/datasets/cifar.py", line 18, in load_batch
    f = open(fpath, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/home/taimoor/.keras/datasets/cifar-10-batches-py/data_batch_1'

file is present in following directory. i tried by giving  absolute path but couldn't run . getting same error. 
Tried to get help from google and tried many ways that found via searching issue description but... not resolved
I am Stuck..

**Comment by bryanyzhu** [comment]
hi, so what is your environment? like what os, what gpu, etc? Are you using Theano? because my code is Pytorch. It seems that your problem is system setup issue. I suggest you use anaconda, do a clean installation, and run official demos to see it is working.

**Comment by thassan66** [comment]
I don't have gpu. i am running this on cpu, i had a clean installation. 
Can i do this on CPU.

**Comment by bryanyzhu** [comment]
I suppose so. Whenever you see ".cuda()" in the code, just remove it. It should work on CPU too.
