### ISSUE TITLE
Flow_model_accuarcy

### ISSUE THREAD

**Issue by 3DMM-ICME2023** [bryanyzhu/two-stream-pytorch#12]
hi, @bryanyzhu thanks for your nice share!
Wang[1] provide a method called Cross modality pre-training which may improve the flow model performance.

[1]. Temporal Segment Networks: Towards Good Practices for Deep Action Recognition

**Comment by bryanyzhu** [comment]
@liu666666 Hi, thanks for your suggestion. Yes, I actually already used the cross modality pre-training technique. Right now, my resnet101 and resnet152 flow model works good. It is just vgg16 model doesn't yield same performance. So it should be something particular about the VGG network.

**Comment by zed0630** [comment]
@bryanyzhu Hi, have you take the direction of optical flow into consideration? When flipping optical flow image, one should also invert the corresponding pixel value in x(horizontal)/y(vertical) channel, otherwise the direction will stay the same, which is contrast to its real direction.

**Comment by bryanyzhu** [comment]
Hi @zed0630 Thanks for pointing out the mistake, I should do another invert. Will update the code base [here](https://github.com/bryanyzhu/two-stream-pytorch/blob/master/video_transforms.py#L163). Thanks.

**Comment by swathikirans** [comment]
@zed0630 Hi, I didn't get your point about inverting the pixel values in the x/y channels during flipping. Can you elaborate on this?

**Comment by bryanyzhu** [comment]
@swathikirans because when you flip your images, e.g, horizontal flip, the flow at x direction also changes. 

You can refer to this [code snippet](https://github.com/yjxiong/tsn-pytorch/blob/master/transforms.py#L45-L60), i think it will help.

**Comment by swathikirans** [comment]
@bryanzhu. Thank you!
