### ISSUE TITLE
Testing from Video input

### ISSUE THREAD

**Issue by Zumbalamambo** [bryanyzhu/two-stream-pytorch#13]
How do I test it realtime or any video as an input using VideoCapture?

**Comment by bryanyzhu** [comment]
Right now, the input is a folder of frames corresponding to a video as in [here](https://github.com/bryanyzhu/two-stream-pytorch/blob/master/scripts/eval_ucf101_pytorch/spatial_demo.py#L37). Then we evenly sample 25 frames from the video and average the prediction results. 

If you want to do online testing (like streaming video), I suggest you look into [this file](https://github.com/bryanyzhu/two-stream-pytorch/blob/master/scripts/eval_ucf101_pytorch/VideoSpatialPrediction.py), especially line 78. For example, you can have a buffer to store the incoming frames using VideoCapture. Whenever you have 25 frames, you make them into a batch like in line 78, and give it to the model for prediction. Hope this helps.

**Comment by thassan66** [comment]
Can i get your trained model and evaluate it UCF101 to generate results

**Comment by bryanyzhu** [comment]
@taimur99 Sure, but I didn't quite understand your question. I think I already shared my trained models for UCF101 split1 in this repo, both VGG16 and ResNet152 models. And I also share the test script to generate the results. No matter you want to test on UCF101, or test it on any video, or use them as feature extractors, you can just modify the test script a little bit to get what you want. Hope this helps.

**Comment by thassan66** [comment]
Okay, Thanks
