### ISSUE TITLE
Can I get the weight or pretrain model in China?

### ISSUE THREAD

**Issue by zhangxgu** [bryanyzhu/two-stream-pytorch#15]
Hi,
I want to download these two pre-trained models but I can't get the weight from google because in China there is a GWF. 
_Pre-trained RGB_ResNet152 Model Pre-trained Flow_ResNet152 Model_
How can I get these weight?
My email is zhangxgu@126.com.
Thank you very much!
@bryanyzhu

**Comment by hoseong-kim** [comment]
@zhangxgu, 
VPN might be an option.

**Comment by bryanyzhu** [comment]
@zhangxgu I think VPN suggested by @hoseong-kim is good. But if you find it hard to use VPN. I am  uploading the models to baiduyun disk. When I finished uploading, I will post the link here.

**Comment by zhangxgu** [comment]
@bryanyzhu @hoseong-kim  Thank you!!

**Comment by bryanyzhu** [comment]
@zhangxgu The models are in baiduyun now. The rgb model is [here](https://pan.baidu.com/s/1oAdwSJ4) and flow model is [here](https://pan.baidu.com/s/1nwWDt5R). Hope you find them ok.
