### ISSUE TITLE
frame extraction

### ISSUE THREAD

**Issue by chandnikathuria1992** [bryanyzhu/two-stream-pytorch#16]
Hi dear
how r u extracting frames from video?

**Comment by bryanyzhu** [comment]
Hi you can either use opencv or ffmpeg to extract the frames. I suggest using opencv. 

The detailed instructions are [here](https://docs.opencv.org/3.0-beta/doc/py_tutorials/py_gui/py_video_display/py_video_display.html). You can follow the sample in "saving a video" section.  Hope this helps.

**Comment by chandnikathuria1992** [comment]
actually i already have extracted frames using FFmpeg
with folder structure as UCF101\jpg\classname\videoname\image_0001.jpg
now i want to test ur spatial stream.So first i need to run build_file_list.py. For this what should be folder structure for video frames?

**Comment by bryanyzhu** [comment]
Hi, if you already extract your frames, then maybe you can manually write your own script to generate the train/test file list. 

The train file list should look like [this](https://github.com/bryanyzhu/two-stream-pytorch/blob/master/datasets/settings/ucf101/train_rgb_split1.txt). And when your train your model, you use "UCF101\jpg\classname" as DATA_PATH (as you said, this is your folder structure). 

Note that, our image name pattern is default to be img_00001.jpg as written [here](https://github.com/bryanyzhu/two-stream-pytorch/blob/master/datasets/ucf101.py#L129-L135). You can pass your own pattern to the data loading function, or simply change line 133 to `image_%04d.jpg` to fit your case. 

If you want to do test, then the test file list should look like [this](https://github.com/bryanyzhu/two-stream-pytorch/blob/master/scripts/eval_ucf101_pytorch/spatial_testlist01_with_labels.txt).

I am sorry the code is not well organized, don't have time to unify it recently.

**Comment by chandnikathuria1992** [comment]
Thanks !
