### ISSUE TITLE
any idea about how much time will take to train on single 8 gb GPU machine?

### ISSUE THREAD

**Issue by chandnikathuria1992** [bryanyzhu/two-stream-pytorch#17]

**Comment by bryanyzhu** [comment]
For spatial stream, I would say half a day because it only need less than 10K iters. For temporal stream, maybe less than 2 days. If you have SSD drive and a system memory larger than 64GB, then you can expect even faster speed.

**Comment by chandnikathuria1992** [comment]
Thanks for ur prompt reply .
