### ISSUE TITLE
dense_flow issue

### ISSUE THREAD

**Issue by CSer-Tang-hao** [bryanyzhu/two-stream-pytorch#18]
when I run: python build_of.py --src_dir ./UCF-101 --out_dir ./ucf101_frames --df_path <path to dense_flow>
I have an error :build_of.py: error: unrecognized arguments
build_of.py [-h] [--src_dir SRC_DIR] [--out_dir OUT_DIR]
                   [--df_path DF_PATH] [--new_width NEW_WIDTH]
                   [--new_height NEW_HEIGHT] [--num_worker NUM_WORKER]
                   [--num_gpu NUM_GPU] [--out_format {dir,zip}]
                   [--ext {avi,mp4}]

**Comment by bryanyzhu** [comment]
@qijiezhao could you comment on this? Thanks.

**Comment by qijiezhao** [comment]
you may miss argument content of --df_path, or make spell errors of these arguments?

**Comment by bryanyzhu** [comment]
Close it for now due to lack of activities.
