### ISSUE TITLE
[Question] Splits used for pretrained model...

### ISSUE THREAD

**Issue by inkawhich** [bryanyzhu/two-stream-pytorch#20]
Thanks for sharing this repo, it is very helpful. Just a quick question about the pretrained temporal resnet152 model you have for download:

- Was the model ONLY trained on the split01 train set?
- Are the splits you are using the official splits from the UCF101 website?

Thanks for the info!

**Comment by bryanyzhu** [comment]
1. Yes, it was only trained on the split01. 
2. Yes, I am using the official splits. 

Thank you.

**Comment by inkawhich** [comment]
Ok, thank you!
