### ISSUE TITLE
the result of ssn_test.py

### ISSUE THREAD

**Issue by yanpeilun** [bryanyzhu/two-stream-pytorch#23]
Hi yaunjun
Your work is so useful, thank you very much for your open source. I'm  trying to run your code, and I want to know the meaning of  the  ssn_test.py result(variable rst). can you help me point them out in this code project?
thanks a lot

**Comment by bityangke** [comment]
走错片场了把。。。

**Comment by yanpeilun** [comment]
@bityangke  不好意思，导演，我走错片场了。。。。</捂脸笑>

**Comment by bryanyzhu** [comment]
@bityangke Thank you~:D
