### ISSUE TITLE
the problem about pre-trained model

### ISSUE THREAD

**Issue by Tylerjoe** [bryanyzhu/two-stream-pytorch#24]
I download the pre-trained model(ucf101_s1_rgb_resnet152.pth.tar) you give ,but I can't extract the file, Could you please give me some advices? Thanks!

**Comment by bryanyzhu** [comment]
Hi, `.pth.tar` is a format that PyTorch use to store the model. **It is actually not a compressed file**. So you don't need to extract things from it. You can just use `torch.load(ucf101_s1_rgb_resnet152.pth.tar)` to get the model and directly use it.

**Comment by Tylerjoe** [comment]
@bryanyzhu Thanks for your reply，I just start to do this area .Thanks for your patience

**Comment by bryanyzhu** [comment]
No problem, glad I can help.
