### ISSUE TITLE
dense_flow

### ISSUE THREAD

**Issue by kanzaali** [bryanyzhu/two-stream-pytorch#26]
I am facing this error which installing dense flow:

.
.
[ 57%] Building CXX object CMakeFiles/extract_gpu.dir/tools/extract_flow_gpu.cpp.o
[ 64%] Building CXX object CMakeFiles/extract_warp_gpu.dir/tools/extract_warp_flow_gpu.cpp.o
[ 71%] Building CXX object CMakeFiles/pydenseflow.dir/src/py_denseflow.cpp.o
CMakeFiles/Makefile2:141: recipe for target 'CMakeFiles/extract_warp_gpu.dir/all' failed
make[1]: *** [CMakeFiles/extract_warp_gpu.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/extract_cpu.dir/all' failed
make[1]: *** [CMakeFiles/extract_cpu.dir/all] Error 2
CMakeFiles/Makefile2:178: recipe for target 'CMakeFiles/extract_gpu.dir/all' failed
make[1]: *** [CMakeFiles/extract_gpu.dir/all] Error 2
CMakeFiles/Makefile2:215: recipe for target 'CMakeFiles/pydenseflow.dir/all' failed
make[1]: *** [CMakeFiles/pydenseflow.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

How to solve this issue?

**Comment by bryanyzhu** [comment]
Hi, are you using this branch (https://github.com/yjxiong/dense_flow/tree/opencv-3.1)? And when did you see this error, building opencv? 

Installing opencv is a very tricky thing. From your log, I couldn't see any useful information. Could you send the full log to me? It seems the error is before these lines.

**Comment by kanzaali** [comment]
Yes, you are right. OpenCV is quite tricky. Actually, I have installed two versions 3.1 and later 2.4 for a project. I dont know if this can help you. 

![dense_flow](https://user-images.githubusercontent.com/33715985/45134097-b3f20a80-b1d3-11e8-8dfe-626a5c609263.png)
[CMakeError.log](https://github.com/bryanyzhu/two-stream-pytorch/files/2355384/CMakeError.log)

**Comment by bryanyzhu** [comment]
From your error, you can see your system is missing a package named `libImath.so`. Try to see if you can install or download that first.

**Comment by kanzaali** [comment]
unable to install this package :( unable to find any command.

**Comment by bryanyzhu** [comment]
Sorry for the late reply, since I couldn't reproduce your error on my machine. It is hard to debug for you. You can seek help from the `dense_flow` repo, maybe they can give you some help.

**Comment by kanzaali** [comment]
OK Thank you for your reply.
