### ISSUE TITLE
Are optical fow compenents rescaled to [0,255] ?

### ISSUE THREAD

**Issue by pinkfloyd06** [bryanyzhu/two-stream-pytorch#27]
Hello @bryanyzhu ,

Thank you for the work.

In the paper you mentioned that your rescaled the optical flow components to [0,255] before feeding it to temporal netwok. I want to make sure if it also the case for the pretrained flow model resnet152.

Thank you

**Comment by bryanyzhu** [comment]
Yes, it is.

**Comment by pinkfloyd06** [comment]
Hi @bryanyzhu ,

Thank you for your answer. 

A question related to the inputs : 

For both training and testing you have : 
1) 1 single frame per video action extracted at random for the RGB stream
2) 10-frame stacking of optical flow fields (successive) extracted at random for the RGB stream 

Was that your setup ?

Thank you

**Comment by bryanyzhu** [comment]
Yes, it is. But that is for training and validation. For testing, we evenly sample 25 frames/optical flow fields from the video, average to get the final result.

**Comment by Benjiou** [comment]
So , we can't extract features at frame level (for temporal stream). Let's say we have a video of 200 frames.  and the temporal stream requires an input of of  10*2 (10=number of frames). It returns representation for a stacked optical flow of 10 frames. Is there any way to do that for1 frame ?

Thank you @bryanyzhu

**Comment by Benjiou** [comment]
So , we can't extract features at frame level (for temporal stream). Let's say we have a video of 200 frames. and the temporal stream requires an input of of 10*2 (10=number of frames). It returns representation for a stacked optical flow of 10 frames. Is there any way to do that for1 frame ?

Thank you @bryanyzhu

**Comment by bryanyzhu** [comment]
@Benjiou You can still do that if you want. For example, when you want feature for frame I_{1}, you just take I_{1:10} to get the temporal feature. and for frame I_{2}, you take I_{2:11} to get the feature.

In this manner, you will get frame-level feature. It's just there is a lot of overlap, and maybe it doesn't give you much benefit over the clip-level feature.
