### ISSUE TITLE
Flipping in flow 

### ISSUE THREAD

**Issue by artest08** [bryanyzhu/two-stream-pytorch#29]
I have seen that in the test code, for the horizontal flipping of x component of optical flow, the image is reversed and the reversed image is deducted from 255. Why dont we just take the reversed image instead? This is the line 71 of video temporal prediction which is 
255 - img_x[:, ::-1]

Thanks in advance

**Comment by bryanyzhu** [comment]
Hi thank you for bringing this up. Actually I didn't write this part of the code, I borrowed it from this repo (https://github.com/yjxiong/caffe/blob/action_recog/action_python/VideoTemporalPrediction.py), which is the earliest repo on deep CNNs for action recognition. 

I think as long as you keep it consistent, you can use reversed image as well. It is just a kind of data augmentation to make the prediction results more robust.  And `255 - img_x[:, ::-1]` may achieve the best performance.
