### ISSUE TITLE
About pre-trained Model

### ISSUE THREAD

**Issue by y-kl8** [bryanyzhu/two-stream-pytorch#38]
If I want to obtain a new pre-trained Flow_VGG16 Model of other video data, what should I do?

**Comment by bryanyzhu** [comment]
I'm not sure I understand your question, but I assume you want a pre-trained flow_VGG16 model on other datasets. 

Just use the code below,

```
model = flow_vgg16(pretrained=True, num_classes=NUM_CLASSES_IN_NEW_DATASET):
```

**Comment by bryanyzhu** [comment]
Close the issue due to inactivity, feel free to reopen it if more problems come up.
