### ISSUE TITLE
test video

### ISSUE THREAD

**Issue by shijubushiju** [bryanyzhu/two-stream-pytorch#39]
Can the model be directly input video for testing? How do I do that?

**Comment by bryanyzhu** [comment]
You mean loading videos directly as input? No, this codebase doesn't support reading videos, it only supports reading decoded video frames.

**Comment by shijubushiju** [comment]
You mean that I need to break the input video into frames and then test it, is that right?

**Comment by shijubushiju** [comment]
Recently, I want to use my own data set for training and testing. I want to realize the recognition of video behavior

**Comment by bryanyzhu** [comment]
Yes, this repo only support loading frames, so you need to decode video into fames and then test it.

If you want to load videos directly for training and testing, you can use [gluoncv](https://github.com/dmlc/gluon-cv/tree/master/gluoncv/model_zoo/action_recognition) video toolkit. I'm working on that, and it has a much more comprehensive model zoo.

If you need a pytorch codebase, you can also try mmaction.

**Comment by shijubushiju** [comment]
Before, I tried to install mmaction but failed, and there were always various problems. Later, I tried to use Docker to solve the problem of video optical flow calculation
