### ISSUE TITLE
Different running env?

### ISSUE THREAD

**Issue by WangShuu** [bryanyzhu/two-stream-pytorch#41]
Hello,i want to know this  repository can be runned in a different environment like cuda 10 and python 3.7 or higher?

**Comment by bryanyzhu** [comment]
It should be fine. There is no customized operations or losses, so version of cuda and python doesn't matter.

**Comment by WangShuu** [comment]
> It should be fine. There is no customized operations or losses, so version of cuda and python doesn't matter.

thanks

**Comment by WangShuu** [comment]
I still have one question that which version of pytorch do you use in this repository？

**Comment by bryanyzhu** [comment]
Since this repo is done three years ago, I think I did it with pytorch 0.3. It should be compatible with pytorch 0.4, 0.5, 1.0 and 1.1. Starting from pytorch 1.2, there are some API changes that may break the code, but I'm not sure. Maybe just warnings during runtime, feel free to try.

**Comment by WangShuu** [comment]
> Since this repo is done three years ago, I think I did it with pytorch 0.3. It should be compatible with pytorch 0.4, 0.5, 1.0 and 1.1. Starting from pytorch 1.2, there are some API changes that may break the code, but I'm not sure. Maybe just warnings during runtime, feel free to try.

^_^Thank you so much,i will try it.
