### ISSUE TITLE
The number of GPUs?

### ISSUE THREAD

**Issue by WangShuu** [bryanyzhu/two-stream-pytorch#43]
Hello,I double how can i train this code with several GPUs? Since i just tried to run the code "main_sigle_gpu.py",only one GPU began to work.How to solve this problem?

**Comment by bryanyzhu** [comment]
Hi, if you want to train it with multiple GPUs, you can wrap the model with dataparallel like this line of code does,

https://github.com/bryanyzhu/two-stream-pytorch/blob/master/main.py#L179
