### ISSUE TITLE
Problems about VideoSpatialPrediction.py

### ISSUE THREAD

**Issue by hjl1012** [bryanyzhu/two-stream-pytorch#46]
Hello! Thanks for your codes! I have learned a lot from it. But as a beginner, I am a little confused about the code below in VideoSpatialPrediction.py:
# crop
    rgb_1 = rgb[:224, :224, :,:]
    rgb_2 = rgb[:224, -224:, :,:]
    rgb_3 = rgb[16:240, 60:284, :,:]
    rgb_4 = rgb[-224:, :224, :,:]
    rgb_5 = rgb[-224:, -224:, :,:]
    rgb_f_1 = rgb_flip[:224, :224, :,:]
    rgb_f_2 = rgb_flip[:224, -224:, :,:]
    rgb_f_3 = rgb_flip[16:240, 60:284, :,:]
    rgb_f_4 = rgb_flip[-224:, :224, :,:]
    rgb_f_5 = rgb_flip[-224:, -224:, :,:]

    rgb = np.concatenate((rgb_1,rgb_2,rgb_3,rgb_4,rgb_5,rgb_f_1,rgb_f_2,rgb_f_3,rgb_f_4,rgb_f_5), axis=3)

    _, _, _, c = rgb.shape

Why do you code like this? I do not know why we should do that and what they mean.
Looking for your answering!

**Comment by bryanyzhu** [comment]
Sorry for the late reply, this was the 10-crop evaluation setting used in https://arxiv.org/abs/1507.02159 and followed by many papers. Basically, it means to take the four corners and 1 center of the image, and take the flips of these as well. So 1 image, can give you 10 overlapping crops.

**Comment by hjl1012** [comment]
您好，已收到您的邮件，我会尽快处理。（I have received your e-mail. Thank you!）
