### ISSUE TITLE
ModuleNotFoundError: No module named 'torch'

### ISSUE THREAD

**Issue by thassan66** [bryanyzhu/two-stream-pytorch#8]
Unable to run source code.getting error. tried many ways to solve but couldn't.
i am using anaconda latest version. Tunning this command and getting error.
'conda install -c peterjc123 pytorch'

pytorch-0.2.1- 100% |###############################| Time: 0:12:11 727.92 kB/s
pytorch-0.2.1- 100% |###############################| Time: 0:04:07   2.15 MB/s
pytorch-0.2.1- 100% |###############################| Time: 0:01:14   7.19 MB/s

CondaError: CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/peterjc123/win-64/pytorch-0.2.1-py36he6bf560_0.2.1cu80.tar.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

CondaError: CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/peterjc123/win-64/pytorch-0.2.1-py36he6bf560_0.2.1cu80.tar.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

CondaError: CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/peterjc123/win-64/pytorch-0.2.1-py36he6bf560_0.2.1cu80.tar.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

.....
Also disable ssl verification in .condarc . and tried again but same issue occurs again n again. i am googling from last three days but stuck :(

**Comment by bryanyzhu** [comment]
Hi, I don't quite understand your question. Did you install Pytorch well, just can't import torch? Or you haven't installed Pytorch? It seems from your error that you haven't installed pytorch yet. 

I googled online, it seems that it is just hard to download windows's version of Pytorch as referred [here](https://github.com/pytorch/pytorch/issues/2192). So that is why all those Http connection error. Maybe you can start a thread in pytorch windows forum to see if anyone can help you. I didn't run into such problems before, sorry.

**Comment by thassan66** [comment]
I have installed pytorch. 3 have been installed but after that iam getting this error.
 CondaError: CondaHTTPError: HTTP 000 CONNECTION FAILED for url 
I have disable ssl verification . but could't get success.
i am unable to run your code.

**Comment by bryanyzhu** [comment]
So if this is case, could you run a simple example [pytorch mnist tutorial](https://github.com/pytorch/examples/tree/master/mnist)? Because this definitely doesn't look like a code problem, it is like a setup issue.
