### ISSUE TITLE
A new error about input.size[1]

### ISSUE THREAD

**Issue by Blankit** [bryanyzhu/two-stream-pytorch#9]
Hello! It's very nice of you to modify *main_single_gpu.py*. I found you change the parameter *new_length* from 10 to 1. Does  *new_length*  represent the number of frames fed into the network? When I change  *new_length*'s value, I get an error **RuntimeError Need input.size[1] == 3 but got xx instead**

**Comment by bryanyzhu** [comment]
Yes, new_length represent the number of frames fed into the network. So new_length = 1 means in RGB spatial mode (the input to CNN would be 224 X 224 X 3), and new_length = 10 means in flow temporal mode (the input to CNN would be 224 X 224 X 20). 

In your case, the error means your input dimension doesn't match those two cases as above. You can try to find where the error is by checking input dimensions. 

I am sorry that, for now, the models in this repo are hard coded, only accept 3-channel rgb images and 20 channel optical flow images. I will change the hard code to parameters soon, and you may not have such issues. But for now, just find where is the error, and change the dimension is fine.

**Comment by Blankit** [comment]
Thanks for your reply,  bryanyzhu.
Expect for your new version.
